@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml

HIDE_STEREOTYPE()

Person(members, "Customer", "Team Members", $sprite="users")
Person(person, "User")
Container(leetcode, "Question", "Leetcode")
Container(github, "New Folder", "Github")
System(answer, "Answer")


Rel(person, leetcode, "Copy link")
Rel(leetcode, github, "Create")
Rel(github, members, "Discuss")
Rel(members, answer, "Upload")
@enduml

